from PyQt6 import QtCore, QtGui, QtWidgets

centralwidget = QtWidgets.QWidget()
centralwidget.setObjectName("centralwidget")
label = QtWidgets.QLabel(parent=centralwidget)
label.setGeometry(QtCore.QRect(220, 20, 261, 61))
font = QtGui.QFont()
font.setFamily("Times New Roman")
font.setPointSize(20)
font.setBold(True)
font.setWeight(75)
label.setFont(font)
label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
label.setObjectName("label")
lineEdit = QtWidgets.QLineEdit(parent=centralwidget)
lineEdit.setGeometry(QtCore.QRect(230, 150, 231, 51))
lineEdit.setObjectName("lineEdit")
pushButton = QtWidgets.QPushButton(parent=centralwidget)
pushButton.setGeometry(QtCore.QRect(300, 240, 91, 31))
font = QtGui.QFont()
font.setFamily("Times New Roman")
font.setPointSize(12)
pushButton.setFont(font)
pushButton.setObjectName("pushButton")
label_2 = QtWidgets.QLabel(parent=centralwidget)
label_2.setGeometry(QtCore.QRect(130, 280, 441, 20))
label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
font = QtGui.QFont()
font.setFamily("Times New Roman")
font.setPointSize(11)
label_2.setFont(font)
label_2.setObjectName("label_2")
pushButton_2 = QtWidgets.QPushButton(parent=centralwidget)
pushButton_2.setGeometry(QtCore.QRect(210, 340, 111, 31))
pushButton_2.setObjectName("pushButton_2")
pushButton_3 = QtWidgets.QPushButton(parent=centralwidget)
pushButton_3.setGeometry(QtCore.QRect(380, 340, 91, 31))
pushButton_3.setObjectName("pushButton_3")

label.setText("Угадай Число!")
pushButton.setText("Ввод")
label_2.setText("Осталось попыток: 10")
pushButton_2.setText("Сыграть ещё раз?")
pushButton_3.setText("Выйти!")